### ISSUE TITLE
Update Java to 14

### ISSUE THREAD

**Issue by ybiquitous** [sider/devon_rex#141]
https://jdk.java.net/13/

**Comment by ybiquitous** [comment]
We may be able to the official Docker image:

https://hub.docker.com/_/openjdk/?tab=tags&page=1&name=13

**Comment by yykamei** [comment]
Yes, absolutely, we can use the official image.

**Comment by ybiquitous** [comment]
Java 14 is now available:

https://hub.docker.com/_/openjdk/?tab=tags&page=1&name=14
