### ISSUE TITLE
Install pip explicitly

### ISSUE THREAD

**Issue by ybiquitous** [sider/devon_rex#359]
We can view the following warning in analysis logs for Flake 8:

```
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

Should we install `pip` explicitly like Pipenv?

https://github.com/sider/devon_rex/blob/746bfaca8f510d2b58691625cbedb9117bb69fbe/.env#L9

**Comment by yykamei** [comment]
Reasonable.

**Comment by ybiquitous** [comment]
Thanks. It seems that `python -m pip install --upgrade pip` updates `pip` to the latest version, but can we update any version we want via `.env` as follows?

```
# .env
PIP_VERSION=20.3.1
```

**Comment by yykamei** [comment]
Yes, you can install the specific version like this:

```console
python -m pip install pip==20.3.1
```

**Comment by ybiquitous** [comment]
Thanks. Can we manage the version of `pip` in `Pipfile`? If yes, we can receive updates from Dependabot.

**Comment by yykamei** [comment]
Yes, it works, but I'm not sure there could be potential flaws with this. I believe we can do this.

**Comment by ybiquitous** [comment]
Ok, let's try it.

BTW, it seems good to always add `--disable-pip-version-check` to the `pip` command to suppress the warning above, so what do you think?

```console
$ pip help | grep -A3 disable-pip-version-check
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
```

**Comment by yykamei** [comment]
Agreed. We don't have to care about whether using old versions as long as we manage the version.
