### ISSUE TITLE
Update Swift to 5.4

### ISSUE THREAD

**Issue by ybiquitous** [sider/devon_rex#565]
When SwiftLint supports Swift 5.4, we can update.

https://github.com/realm/SwiftLint/blob/9939c536d5159d043a9bd47f40006ff687a99dac/azure-pipelines.yml#L12

https://github.com/sider/devon_rex/blob/6df21e6ff9bc68fe65b07be9d723bd7b2c7609f9/swift/Dockerfile#L37

See also #542

**Comment by radomirbosak** [comment]
5.4 seems to be supported
https://swiftpackageindex.com/realm/SwiftLint
![image](https://user-images.githubusercontent.com/4988740/140712686-3e0c0160-07f6-4d9a-a0dc-9cb776dc68eb.png)

**Comment by radomirbosak** [comment]
Also 5.4 is used in SwiftLint's CI
https://github.com/realm/SwiftLint/blob/5a98458d94d623ba7ea1a86769aa7685d4fc86f8/azure-pipelines.yml#L12-L13

**Comment by radomirbosak** [comment]
This is however SwitfLint version `0.45.0` . We are still using `0.44.0` in `runners`.

**Comment by radomirbosak** [comment]
We've already updated the base image to Swift `5.5.1` in `devon_rex`
https://github.com/sider/devon_rex/pull/699

So I think we can just update SwiftLint too in the next release, and not worry about `0.44.0` compatibility
https://github.com/sider/runners/pull/2765

**Comment by radomirbosak** [comment]
Fixed by https://github.com/sider/devon_rex/pull/699
