### ISSUE TITLE
LC_ALL warning

### ISSUE THREAD

**Issue by ybiquitous** [sider/devon_rex#59]
`docker run` outputs the following warning:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Is the `LC_ALL` environment variable needed?

https://github.com/sider/devon_rex/blob/0eee329fa2d3dfcf7d19ba25f34b0ee1eb8fb42a/base/Dockerfile.env.erb#L8

**Comment by yykamei** [comment]
This is the specific problem of #58.
